---
title: "Untitled"
author: "jpmarindiaz"
date: "May 7, 2015"
output: 
  html_document:
    self_contained: FALSE
---

```{r}
library(d3plus)


data <- tblpkg::sampleData("CNN")
type <- "tree"
d3plus(data,"tree")

d3plus(data[c(1,3,2)],"tree")

data <- tblpkg::sampleData("DNNNN")
d3plus(data,"lines")



# 
# tblpkg::availableSampleData()
# data <- tblpkg::sampleData("CN")
# d3plusTree(data)
# 
# d3plusLines(tblpkg::sampleData("DNNNN"))
#d3plusLines(tblpkg::sampleData("DNNNN"))


# data2 <- tblpkg::sampleData("CNN")
# d3plusTree(data2[c(1,3,2)])


```



## simpleNetwork

```{r}
library(networkD3)
src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
networkData <- data.frame(src, target)
simpleNetwork(networkData)

data(MisLinks)
data(MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4)

URL <- "https://raw.githubusercontent.com/christophergandrud/d3Network/sankey/JSONdata/energy.json"
Energy <- RCurl::getURL(URL, ssl.verifypeer = FALSE)
EngLinks <- JSONtoDF(jsonStr = Energy, array = "links")
EngNodes <- JSONtoDF(jsonStr = Energy, array = "nodes")

sankeyNetwork(Links = EngLinks, Nodes = EngNodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              fontsize = 12, nodeWidth = 30)

Flare <- RCurl::getURL("https://gist.githubusercontent.com/mbostock/4063550/raw/a05a94858375bd0ae023f6950a2b13fac5127637/flare.json")
Flare <- rjson::fromJSON(Flare)
treeNetwork(List = Flare, fontSize = 10, opacity = 0.9, margin=0)
```


